# Install longhorn
- name: Add longhorn repo
  ansible.builtin.command:
    cmd: helm repo add longhorn https://charts.longhorn.io
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Update helm repo
  ansible.builtin.command:
    cmd: helm repo update
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Install longhorn
  ansible.builtin.command:
    cmd: helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]