---
os: "linux"
arch: "amd64"

vip: 192.168.10.50

metallb_version: v0.13.12
lb_range: 192.168.10.90-192.168.10.100
lb_pool_name: first-pool

ansible_become: true
ansible_become_method: sudo
################################################################################
# options to change default values
# kube_vip_version: "v0.8.3"
# vip_interface: "eth0"
# rke2_version: "v1.30.5+rke2r1"
# rke2_install_dir: "/usr/local/bin"
