# Install helm chart
- name: Check helm exist
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_exist
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['servers'][0]

- name: Download helm chart
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
    dest: /tmp/get_helm.sh
    mode: '0700'
    force: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['servers'][0] and helm_exist.stat.exists == false

- name: Install helm chart
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and helm_exist.stat.exists == false

# Install cert manager
- name: Check cert manager exist
  ansible.builtin.command:
    cmd: kubectl get pods --namespace cert-manager
  register: cert_manager_exist
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Add cert manager crds
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.crds.yaml
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and cert_manager_exist.stdout == "No resources found in cert-manager namespace."

- name: Add jetstack repo
  ansible.builtin.command:
    cmd: helm repo add jetstack https://charts.jetstack.io
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and cert_manager_exist.stdout == "No resources found in cert-manager namespace."

- name: Update helm repo
  ansible.builtin.command:
    cmd: helm repo update
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and cert_manager_exist.stdout == "No resources found in cert-manager namespace."

- name: Install cert manager
  ansible.builtin.command:
    cmd: helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.16.1
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and cert_manager_exist.stdout == "No resources found in cert-manager namespace."

- name: Roll out cert-manager status
  ansible.builtin.command:
    cmd: kubectl rollout status deploy/cert-manager --namespace cert-manager
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

# Install rancher
- name: Check rancher exist
  ansible.builtin.command:
    cmd: kubectl get pods --namespace cattle-system
  register: rancher_exist
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Add rancher repo
  ansible.builtin.command:
    cmd: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and rancher_exist.stdout == "No resources found in cattle-system namespace."

- name: Update helm repo
  ansible.builtin.command:
    cmd: helm repo update
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and rancher_exist.stdout == "No resources found in cattle-system namespace."

- name: Install rancher
  ansible.builtin.command:
    cmd: helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=rancher.tmdsite.my.id --set bootstrapPassword=admin
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and rancher_exist.stdout == "No resources found in cattle-system namespace."

- name: Roll out rancher status
  ansible.builtin.command:
    cmd: kubectl rollout status deploy/rancher --namespace cattle-system
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

# Expose Rancher
- name: Check rancher loadbalancer exist
  ansible.builtin.command:
    cmd: kubectl get svc rancher-lb -n cattle-system
  register: rancher_lb_exist
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Expose rancher via Loadbalancer
  ansible.builtin.command:
    cmd: kubectl expose deployment rancher --name=rancher-lb --port=443 --type=LoadBalancer -n cattle-system
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and rancher_lb_exist.stdout == 'Error from server (NotFound): services "rancher-lb" not found'

- name: Get rancher loadbalancer ip
  ansible.builtin.command:
    cmd: kubectl get svc rancher-lb -n cattle-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: rancher_lb_ip
  become_user: "{{ ansible_user }}"
  changed_when: false
  when: inventory_hostname == groups['servers'][0]

- name: Print rancher loadbalancer ip
  ansible.builtin.debug:
    msg: "Rancher IP: {{ rancher_lb_ip.stdout }}"
  when: inventory_hostname == groups['servers'][0]