- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Purge snapd and autoremove unused packages
  apt:
    name: snapd
    state: absent
    purge: yes
    autoremove: yes
  retries: 5
  delay: 10
  register: apt_remove_result
  until: apt_remove_result is succeeded

- name: Hold snapd package to prevent reinstallation
  command: apt-mark hold snapd
  register: apt_hold_result
  changed_when: "'snapd set on hold.' in apt_hold_result.stdout"

- name: Stop multipathd service
  systemd:
    name: multipathd.service
    state: stopped
    enabled: false

- name: Stop multipathd socket
  systemd:
    name: multipathd.socket
    state: stopped
    enabled: false